sequenceDiagram
    Actor A
    Participant ViewTCP A
    Participant PlayerControllerTCP A
    Participant Player A
    Participant Match
    Participant Player B
    Participant PlayerControllerRMI B
    Participant ViewRMI B
    Actor B

    A ->> ViewTCP A: "Play Card"
    ViewTCP A->>PlayerControllerTCP A: action: PlayCard
    PlayerControllerTCP A ->> Player A: player.playCard()
    Player A ->> Match: match.makeMove()
    Match ->> PlayerControllerRMI B: observer.someonePlayedCard()
    PlayerControllerRMI B ->> ViewRMI B: view.someonePlayedCard()
    ViewRMI B ->> B: "Show changes"
    Match ->> PlayerControllerTCP A: observer.someonePlayedCard()
    PlayerControllerTCP A ->> ViewTCP A: response: SomeonePlayedCard
    ViewTCP A ->> A: "Show changes"
    B ->> ViewRMI B: "draw secret objectives"
    ViewRMI B ->> PlayerControllerRMI B: playerController.drawSecretObjective()
    PlayerControllerRMI B ->> Player B: player.drawSecretObjective()
    Player B ->> Match: match.drawSecretObjective()
    Match ->> PlayerControllerTCP A: observer.someoneDrewSecretObjective()
    PlayerControllerTCP A ->> ViewTCP A: response: SomeoneDrewSecretObjective
    ViewTCP A ->> A: "Show changes"
    Match ->> PlayerControllerRMI B: observer.someoneDrewSecretObjective()
    PlayerControllerRMI B ->> ViewRMI B: view.giveSecretObjective()
    ViewRMI B ->> B: "show secret objectives"
