---
title: Model diagram
---
classDiagram
    Match --> GameDeck
    Match --> MatchState
    Match --> DrawSource
    Match -- Player
    MatchState <|-- WaitState
    MatchState <|-- NextTurnState
    MatchState <|-- ChooseInitialSideState
    MatchState <|-- ChooseSecretObjectiveState
    MatchState <|-- AfterMoveState
    MatchState <|-- AfterDrawState
    MatchState <|-- FinalState

    Card <|-- InitialCard
    Card <|-- PlayableCard
    GameDeck --> Card
    PlayableCard <|-- ResourceCard
    PlayableCard <|-- GoldCard

    Board -- PlacementOutcome
    Requirement <|-- QuantityRequirement
    Requirement <|-- PositionRequirement
    Requirement <-- Objective
    QuantityRequirement <-- GoldCard

    Board --> PlacedCard
    Side <-- PlacedCard
    Player --> Board
    Player --> Objective
    Player --> Color
    CardFace <-- Card
    Symbol <-- CardFace
    Board --> Requirement
    %%Side <-- Player
    %%Side <-- Match
    Corner <-- CardFace
    %%Symbol <-- GoldCard
    %% DrawSource <-- Player



    class Symbol {
        <<Enumeration>>
        ANIMAL
        PLANT
        INSECT
        FUNGUS
        FEATHER
        INKWELL
        PARCHMENT
        EMPTY_CORNER
        FULL_CORNER
        CORNER_OBJ
    }

    class Corner {
      <<Enumeation>>
      TOP_LEFT
      TOP_RIGHT
      BOTTOM_LEFT
      BOTTOM_RIGHT
    }

    class CardFace {
        <<Record>>
        - topLeft: Symbol
        - topRight: Symbol
        - bottomLeft: Symbol
        - bottomRight: Symbol
        - center: Set~Symbol~
        + CardFace(Symbol topLeft, Symbol topRight, Symbol bottomLeft, Symbol bottomRight, Set~Symbol~ center)
        + getCorner(Corner corner) Symbol
        + getCenter() Set~Symbol~
    }

    class Card {
        <<Abstract>>
        # sides : Map~Side, CardFace~
        + getSide(Side side) CardFace
    }

    class PlayableCard {
        <<Abstract>>
        # reign: Symbol
        # points: int
        + PlayableCard(Symbol reign)
        + getReign() Symbol
    }

    class InitialCard {
        + InitialCard(CardFace front, CardFace back)
    }

    class ResourceCard {
        + ResourceCard(CardFace front, Symbol reign, int points)
        + getPoints() int
    }

    class GoldCard {
        - multiplier: Symbol
        - req: QuantityRequirement
        + GoldCard(CardFace front, Symbol reign, int points, Symbol multiplier, QuantityRequirement req)
        + getMultiplier() Symbol
        + getRequirement() QuantityRequirement
        + calculatePoints(Board board, Pair~Integer, Integer~ coord) int
    }

    class Requirement {
        <<Abstract>>
        - Requirement()
        + timesMet(Board board) int
    }

    class QuantityRequirement {
        - reqs : Map~Symbol, Integer~
        + QuantityRequirement(Symbol simbol, Integer quantity)
        + timesMet(Board board) int
    }

    class PositionRequirement {
        - reqs: Map&ltPair&ltInteger, Integer&gt, Color&gt
        + PositionRequirement(Map&ltPair&ltInteger, Integer&gt, Color&gt)
        + timesMet(Board board) int
    }
    class Objective {
        - points: int
        - req: Requirement
        + Objective(int points, Requirement req)
        + getPoints() int
        + getRequirement() Requirement
    }
    class Player {
        - nickname: String
        - match: Match
        - points: Int
        - board: Board
        - color: Color
        - objective: Objective

        + Player(String nickname, Match match)
        + playCard(Pair<Integer, Integer> coord, PlayableCard card, Side side) void
        + drawCard(DrawSource draw) void
        + chooseObjective(Objective objective) void
        + chooseInitialSide(Side side) void
        + getBoard() Board
        + getPoints() int
        + getSecretObjective() Objective
        + getColor() Color
        + getNickname() String
        # setColor() void
    }
    class Color{
        <<Enumeration>>
        RED
        BLUE
        GREEN
        YELLOW
    }
    class Side{
        <<Enumeration>>
        FRONT
        BACK
    }
    class Board {
        - currentHand: List~PlayableCard~
        - placed: Map&ltPair&ltInteger,Integer&gt, PlacedCard&gt
        - availableResources: Map~Symbol, Integer~

        + Board()
        + getAvailableResources() Map~Symbol, Integer~
        + getPlacedCards() Map&ltPair&ltInteger, Integer&gt, PlacedCard&gt
        + getCurrentHand() List~PlayableCard~
        # removeHandCard(PlayableCard card) void
        # addHandCard(PlayableCard card) void
        # setInitialCard(InitialCard card, Side side) void
        # placeCard(Pair~Integer, Integer~ coord, PlayableCard card, Side side, int turn) int
        + verifyCardPlacement(Pair~Integer, Integer~ coords, Card card, Side side) PlacementOutcome
    }
    class PlacedCard {
        <<Record>>
        - card: Card
        - turn: int
        + PlacedCard(Card card, int turn)
        + getCard() Card
        + getTurn() int
    }

    class Match {
        - players: list~Players~
        - maxPlayers: int
        - currState: MatchState
        - currentPlayer: Player
        - initialsDeck: GameDeck~InitialCard~
        - resourcesDeck: GameDeck~ResourceCard~
        - goldsDeck: GameDeck~GoldCard~
        - objectivesDeck: GameDeck~Objective~
        - visibleGolds: Pair~GoldCard, GoldCard~
        - visibleResources: Pair~ResourceCard, ResourceCard~
        - visibleObjectives: Pair~Objective, Objective~
        - currentProposedObjectives: Pair~Objective, Objective~
        - currentGivenInitialCard: InitialCard
        - started: bool
        - initialTurn: bool
        - lastTurn: bool
        - finished: bool

        + Match(int maxPlayers, resourceDeck ) void
        + isFull() bool
        + isStarted() bool
        + isInitialTurnFinished() bool
        + isFinished() bool
        + addPlayer(Player player) void
        + removePlayer(Player player) void
        + getCurrentPlayer() Player
        + getPlayers() List~Player~
        + getMaxPlayers() int
        # getPoints() int
        # addPoints() void
        # setSecretObjective(Objective obj) void
        # proposeSecretObjectives() Pair~Objective, Objective~
        # makeMove(Pair~Integer, Integer~ coords, PlayableCard card, Side side) void
        # drawCard(DrawSource draw) PlayableCard
        # setInitialSide(Side side) void
        # doStart() void
        # doInitialTurnFinish() void
        # doFinish() void
        # setState() void
        # setupDecks() void
        # setupPlayers() void
        # setupBoards() void
        # nextPlayer() void

    }
    class DrawSource {
        <<Enumeration>>
        GOLDS_DECK,
        RESOURCES_DECK,
        FIRST_VISIBLE,
        SECOND_VISIBLE,
        THIRD_VISIBLE,
        FOURTH_VISIBLE
    }

    class MatchState {
        <<Abstract>>
        + match: Match
        + MatchState(Match match)
        + transition() void
        + addPlayer() void
        + removePlayer() void
	    + proposeSecretObjectives() void
	    + chooseSecretObjective() void
        + chooseInitialSide() void
        + drawInitialCard() void
	    + makeMove() void
	    + drawCard() void

    }

    class WaitState{
        + WaitState(Match match) void
        + transition() void
        + addPlayer() void
        + removePlayer() void
    }
    class NextTurnState {
        + NextTurnState(Match match) void
        + proposeSecretObjectives() void
        + makeMove() void
        + drawInitialCard() void
        + transition() void
    }
    class ChooseInitialSideState{ 
        + ChooseInitialSideState(Match match) void
        + chooseInitialSide(Side side) void
        + transition() void
    }
    class ChooseSecretObjectiveState {
        + ChooseSecretObjectiveState() void
        + chooseSecretObjective() void
        + transition() void
    }

    class AfterMoveState {
        + AfterMoveState() void
        + drawCard() void
        + transition() void
    }

    class AfterDrawState {
        + AfterDrawState() void
        + transition() void
    }

    class FinalState{
        + FinalState() void
        + transition() void
    }

    class PlacementOutcome {
        <<Enumeration>>
        VALID,
        INVALID_COORDS,
        INVALID_ENOUGH_RESOURCES,
    } 
    class GameDeck {
        <<Generics>>
        - cardsList: List~C~
        + GameDeck()
        + add(C card) void
        + getSize() int
        + pop() C
        + poll() C
        + shuffle() void
        + isEmpty() void
    }

